[Feat/ONE4-76] 게시글 목록 전체 조회 API 구현
TmaxFintech/SAS_Research_1-4 pull request #8
Opened 2024-07-10 06:40 UTC by Bellroute

## 👉 기능 설명
- 게시글 목록을 전체 조회해오는 api
- 페이지 번호(pageNum)와 페이지 크기(pageSize)를 입력받아 페이징 처리된 목록을 제공한다.

## 👉 요청 및 질문사항
- API 명세 상으로는 삭제 처리(is_deleted=true)된 게시글을 제외한다는 요구사항이 없는 것으로 보여 제외하였습니다. 반영 필요한지 확인 필요해보입니다.
- 쿼리 질의를 통해 받아온 Dto 객체와 api의 응답으로 보내질 Dto 객체를 분리하는 것과 통합하는 것 중 어느쪽이 더 이로울지 고민이 되었습니다. 
- 쿼리 질의를 통해 받아온 Dto 객체의 멤버로 또다른 Dto 객체를 두기 위해 mybatis의 xml에 resultMap을 정의해줬습니다. 코드와 xml 둘 다 작성해야한다는 점에서 불편하고 실수가 많이 나올 것으로 보이는데 좋은 방법이 없을지 mybatis에 대해 조금 더 알아야할 필요성을 느꼈습니다.

2024-07-10 07:26 UTC, YGwan requested changes
고생하셨습니다.

TypeHandle부터 Join문까지 구현하시느라 고생 많으셨습니다!!

2024-07-10 07:26 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +            case "0" -> {
여기서 말하는 0과 1은 enum값의 순서일까요?

2024-07-10 07:26 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/dto/request/RetrieveArticlesRequest.java
> +    private Integer curPageNum;
해당 dto에만 final 키워드가 안 붙은 이유가 따로 있을까요?

2024-07-10 07:26 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +        return getValueEnum(value);
해당 로직이 실행된다는 것은 value값이 N & Y가 아닐 때인 것으로 확인되는데 맞을까요? 맞다면 해당 메서드는 왜 필요한건가요?

2024-07-10 07:26 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/repository/ArticleRepository.java
> +    List<RetrieveArticlesResponse> findAll();
TypeHandler 구현을 완료하셨으니 해당 자료형은
List<Article> 이 되는게 더 자연스러운 흐름이 아닐까요?

2024-07-10 07:26 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/repository/Pagination.java
> +    public Pagination(int pageNo, int amount) {
통일성 있게 해당 부분도 `@RequiredArgsConstructor`를 사용하시는건 어떠신가요?

혹시 해당 어노테이션 사용을 지양하신다면 제가 맞추겠습니다!

2024-07-10 07:44 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +            case "0" -> {
넵! 다만 정확히 발생하는 경우를 파악못해서 조금 더 확인 필요할 것 같습니다!

2024-07-10 07:46 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +        return getValueEnum(value);
value가 N , Y가 아닌 0, 1로 읽히는 경우가 있는 것 같더라구요. 예외적으로 for문을 통과해버리는 경우가 있어서 그부분 처리하고자 추가했습니다.

2024-07-10 07:47 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/repository/Pagination.java
> +    public Pagination(int pageNo, int amount) {
pageNo 가 0이거나 amount가 0인 경우 데이터가 조회가 안되는 경우가 있어서 default처리를 해둘까 싶어서 생성자를 만들었었는데 당장은 어노테이션 붙여놓는게 통일되겠네요 수정해두겠습니다!

2024-07-10 07:48 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/dto/request/RetrieveArticlesRequest.java
> +    private Integer curPageNum;
단순 누락입니다.. 발견 감사해요:)

2024-07-10 07:55 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/repository/ArticleRepository.java
> +    List<RetrieveArticlesResponse> findAll();
이부분 용관님 코드에도 조금 영향이 갈 거 같은데 어떻게 할까요..? 해당 Response에는 String userId 대신 UserInArticleResponse user 라는 멤버가 있어서요

2024-07-10 07:57 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/repository/Pagination.java
> +    public Pagination(int pageNo, int amount) {
아아 추가적인 검증 로직을 생성자에서 처리하실 계획이시면 납두셔도 좋습니다!!

2024-07-10 07:58 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/repository/ArticleRepository.java
> +    List<RetrieveArticlesResponse> findAll();
아아 제가 잘못 이해했군요!! 이건 종근님이 하신대로 하시면 될거 같습니다!! 이후에 제가 수정할께요!!

2024-07-10 08:01 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +        return getValueEnum(value);
아아 그럼 value 값은 N & Y인데, 0 1 순서로 읽히는 문제군요
혹시 그러면, 실제 requestBody에 isDeleted 값에 0 or 1 값을 넣어서 요청을 보내면 에러를 정상적으로 발생시키나요?

2024-07-10 08:02 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +            case "0" -> {
저도 이후에 확인해보겠습니다!!

2024-07-10 09:47 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +        return getValueEnum(value);
Article을 생성할 때 말씀이실까요?

2024-07-10 13:16 UTC, YGwan commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeleted.java
> +        return getValueEnum(value);
아 이 부분은 조회시니 문제가 없겠군요!!
제가 헷갈렸네요!!

2024-07-10 13:16 UTC, YGwan commented
수고하셨습니다!!

2024-07-10 13:16 UTC, YGwan approved these changes

2024-07-11 00:27 UTC, good-da22 commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeletedTypeHandler.java
IsDeleted가 모든 테이블에서 사용중인 컬럼이고 역할 또한 컬럼의 유효성을 확인하는 목적으로 동일하기 때문에
해당 내용을 article 도메인 안에서 정의하기 보다는 공통으로 빼서 처리하는거 어떨까요?

2024-07-11 00:27 UTC, good-da22 commented on src/main/java/com/tmax/fintech/article/dto/response/RetrieveArticlesResponse.java
> +@Data
어노테이션을 세분화하지 않고 Data 어노테이션을 사용한 이유가 따로 있을까요?
공제회 코드짤때 초반에도 비슷한 내용이 있었던 걸로 기억합니다!

2024-07-11 03:45 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/dto/response/RetrieveArticlesResponse.java
> +@Data
롬복이 다 적용되는지 싶어서 @Data를 임시적으로 넣어둔 부분이었습니다!

2024-07-11 03:46 UTC, Bellroute commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeletedTypeHandler.java
넵 좋은 것 같습니다

2024-07-11 03:56 UTC, good-da22 commented on src/main/java/com/tmax/fintech/article/domain/constant/IsDeletedTypeHandler.java
이 부분만 반영되면 다른 부분은 머지해도될것같습니다! 수고하셨습니다!

2024-07-11 04:17 UTC, merged